[theme]
base = "light"
primaryColor = "#16243A"
backgroundColor = "#F4F6F8"
secondaryBackgroundColor = "#EDF0F3"
textColor = "#16243A"
font = "Anek Latin, sans-serif"

[[theme.fontFaces]]
family = "Anek Latin"
url = "app/static/AnekLatin.ttf"

[server]
enableStaticServing = true
headless = true
maxUploadSize = 50

[browser]
gatherUsageStats = false
